
package frames;

import akinator.myheroacademia.Akinator_BNHA_Game;
import akinator.myheroacademia.QuestionManager;
import javax.swing.SwingConstants;

/*@author Beatriz Alves */
public class Final_Interface extends javax.swing.JFrame {

    private Akinator_BNHA_Game finalCharacter;
    
    public Final_Interface(Akinator_BNHA_Game game) {
        this.finalCharacter = game;
        initComponents();
        setLocationRelativeTo(null);
        Show_FinalCharacter();
    }
    
    private void Show_FinalCharacter() {
        // Obtém o nome do personagem final do jogo e o exibe na JLabel FinalCharacter
        String characterName = finalCharacter.getFinalCharacter(); // Supondo que Akinator_game tenha um método getCharacter()
        FinalCharacter.setText(characterName);
        FinalCharacter.setText("<html> <div style='text-align: center;'>" + FinalCharacter.getText().replace("\n", "<br>") + "</div></html>");
        FinalCharacter.setHorizontalAlignment(SwingConstants.CENTER); // Centralizar o texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FinalCharacter = new javax.swing.JLabel();
        finish_game = new javax.swing.JButton();
        try_again = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seu personagem é:");

        FinalCharacter.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        FinalCharacter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FinalCharacter.setText("jLabel2");
        FinalCharacter.setAutoscrolls(true);
        FinalCharacter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        finish_game.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finish_game.setText("Finalizar Jogo");
        finish_game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finish_gameMouseClicked(evt);
            }
        });
        finish_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_gameActionPerformed(evt);
            }
        });

        try_again.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        try_again.setText("Tentar  Novamente");
        try_again.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try_againMouseClicked(evt);
            }
        });
        try_again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try_againActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FinalCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(finish_game, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(try_again, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(FinalCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finish_game, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(try_again, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finish_gameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finish_gameMouseClicked
        // Finalizar o jogo

        // Fecha o aplicativo completamente
        System.exit(0);
    }//GEN-LAST:event_finish_gameMouseClicked

    private void finish_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finish_gameActionPerformed

    private void try_againMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_try_againMouseClicked
        // Voltar para a Second_interface

        // Fechar o JFrame atual
        this.dispose();
        QuestionManager game = new QuestionManager(/* parâmetros necessários */);
        new Game_Interface().setVisible(true);
        System.out.println("\n----------------------------------------------\n");
    }//GEN-LAST:event_try_againMouseClicked

    private void try_againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_try_againActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_try_againActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_Interface(new Akinator_BNHA_Game()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinalCharacter;
    private javax.swing.JButton finish_game;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton try_again;
    // End of variables declaration//GEN-END:variables
}
